#!/usr/bin/env bash

clear
sleep 1

#----------------------------->>> Installer for Ubuntu 18.04 LTS Machine
echo " "
echo "----------------------------------------------------------------------------------"
echo "--------->      Installer for Ubuntu 18.04 LTS Machine"
echo "----------------------------------------------------------------------------------"
echo " "
sleep 1
cd ~/Downloads >> /dev/null
sudo apt update
sleep 3

#----------------------------->>> Install Essential Packages
echo " "
echo "----------------------------------------------------------------------------------"
echo "--------->      Install Essential Packages"
echo "----------------------------------------------------------------------------------"
echo " "
sleep 1
while read -r p ; do sudo apt install -y $p ; done < <(cat << "EOF"
    build-essential
    net-tools
    default-jdk
    libssl-dev
    exuberant-ctags
    libncurses5-dev
    ncurses-term
    ack-grep
    vim
    tmux
    silversearcher-ag
    fontconfig
    imagemagick
    libmagickwand-dev
    libwxgtk3.0-dev
    libwxgtk3.0-gtk3-dev
    software-properties-common
    git
    vim-gtk3
    curl
    apt-transport-https
    glibc-source
    whois
    traceroute
    bison
    texinfo
    gawk
    flex
    freetds-dev
    cmake
    gnome-tweak-tool
    fonts-hack-ttf
    figlet
    shutter
    youtube-dl
    ffmpeg
    vlc
    libindicator7
    libc++abi1
    libappindicator1
    libc++1
    pidgin
    rdesktop
    unrar
    zsh
    python-pip
    python3-pip
    snapd
    flatpak
    sendemail
    libgtk*-dev
    fonts-powerline
    mpv
    python3.8
EOF
)
sudo apt update
sleep 3

#----------------------------->>> Install Base Dates
echo " "
echo -n "--------->      Do you want install Data Base PostgreSQL, Redis and MemCache (yes/no) ? "
read opcao
sleep 1
if [ $opcao = "yes" ]; then
	echo " "
	echo "----------------------------------------------------------------------------------"
	echo "--------->      Install Data Bases Packages"
	echo "----------------------------------------------------------------------------------"
	echo " "
	sleep 1
	sudo apt install postgresql-10 postgresql-contrib postgresql-server-dev-10 redis-server libhiredis-dev memcached libmemcached-dev -y
	sleep 3
fi
sleep 3

#----------------------------->>> Install Google Chrome, Opera Browser and Tor Browser
echo " "
echo "----------------------------------------------------------------------------------"
echo "--------->      Install Google Chrome, Opera Browser and Tor Browser"
echo "----------------------------------------------------------------------------------"
echo " "
sleep 1
cd ~/Downloads > /dev/null
wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
sudo apt update && sudo apt-get install google-chrome-stable -y
sleep 1
##########################
echo "deb [arch=i386,amd64] https://deb.opera.com/opera-stable/ stable non-free" | sudo tee -a /etc/apt/sources.list.d/opera-stable.list
sudo  apt update && sudo apt-get install opera-stable -y
sleep 1
##########################
sudo tar -xvf tor-browser* -C /opt
cd /opt >> /dev/null
sudo chown -R $USER:$USER tor-browser_en-US
cd tor-browser_en-US >> /dev/null
printf '#!/usr/bin/env bash\ncd /opt/tor-browser_en-US/ >> /dev/null\n./Browser/start-tor-browser --detach\ncd - >> /dev/null\n' | tee -a tor-laucher
cd /opt/tor-browser_en-US/
sudo chmod +x tor-laucher
cd - >> /dev/null
sudo ln -s /opt/tor-browser_en-US/tor-laucher /usr/bin/tor-browser
cat > ~/.local/share/applications/tor-browser.desktop <<EOL
    [Desktop Entry]
    Encoding=UTF-8
    Name=Tor
    Exec=tor-browser
    Icon=/opt/tor-browser_en-US/Browser/browser/chrome/icons/default/default64.png
    Terminal=false
    Type=Application
    Categories=Browser;
EOL
sleep 3

#----------------------------->>> Install SublimeText, Terminator, Neofetch, AnyDesk, Insomnia, Postman and VisualStudio
echo " "
echo "----------------------------------------------------------------------------------"
echo "--------->      Install SublimeText, Atom, Terminator, Neofetch, AnyDesk, Insomnia, Postman, Heroku-CLI and VisualStudio"
echo "----------------------------------------------------------------------------------"
echo " "
sleep 1
wget -qO - https://download.sublimetext.com/sublimehq-pub.gpg | sudo apt-key add -
echo "deb https://download.sublimetext.com/ apt/stable/" | sudo tee /etc/apt/sources.list.d/sublime-text.list
sudo apt update && sudo apt-get install sublime-text -y
sleep 1
sudo add-apt-repository ppa:webupd8team/atom -y
sudo apt-get update && sudo apt-get install atom -y
sleep 1
sudo add-apt-repository ppa:gnome-terminator/nightly-gtk3 -y
sudo apt update && sudo apt-get install terminator -y
sleep 1
sudo add-apt-repository ppa:dawidd0811/neofetch -y
sudo apt update && sudo apt-get install neofetch -y
sleep 1
wget -qO - https://keys.anydesk.com/repos/DEB-GPG-KEY | sudo apt-key add -
sudo echo "deb http://deb.anydesk.com/ all main" > /etc/apt/sources.list.d/anydesk-stable.list
sudo apt update && sudo apt install anydesk -y
sleep 1
echo "deb https://dl.bintray.com/getinsomnia/Insomnia /"     | sudo tee -a /etc/apt/sources.list.d/insomnia.list
wget --quiet -O - https://insomnia.rest/keys/debian-public.key.asc     | sudo apt-key add -
sudo  apt update && sudo apt-get install insomnia -y
sleep 1
sudo snap install postman
sleep 1
sudo snap install --classic heroku
sleep 1
sudo snap install code --classic
sleep 3

#----------------------------->>> Install Node.js, Npm, Yarn, T-get and Global Development Node Modules
echo " "
echo "----------------------------------------------------------------------------------"
echo "--------->      Install Node.js, Npm, Yarn, Nodemon, NPX, Expo, Serve, TypeORM, Reactotron, Deno and Global Development Node Modules "
echo "----------------------------------------------------------------------------------"
echo " "
sleep 1
sudo curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash -
sudo apt install -y nodejs
sleep 1
curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
sudo apt update && sudo apt install --no-install-recommends yarn
echo '    --->Testing Node, Npm & Yarn'
node -v
npm -v
yarn --version
sleep 1
sudo npm install -g nodemon
# sleep 1
# sudo yarn global add gluegun
sleep 1
sudo npm install -g npx
sleep 1
sudo npm install -g expo-cli
sleep 1 
sudo npm install -g serve
sleep 1 
yarn global add typeorm
sleep 1 
cd ~/Downloads > /dev/null
wget https://github.com/infinitered/reactotron/releases/download/v2.17.1/reactotron-app_2.17.1_amd64.deb
sudo apt install -y ./reactotron-app_2.17.1_amd64.deb
sleep 1
curl -fsSL https://deno.land/x/install/install.sh | sh
cat >> ~/.bashrc << EOL
    alias deno='/home/vinicius/.deno/bin/deno'
EOL
deno --version
sleep 1
sleep 3

#----------------------------->>> Install Python, Pip, bPython, SciKit-Learn and Global Development Python Modules
echo " "
echo "----------------------------------------------------------------------------------"
echo "--------->      Install Python, Pip, bPython, SciKit-Learn and Global Development Python Modules "
echo "----------------------------------------------------------------------------------"
echo " "
sleep 1
sudo apt install software-properties-common
sudo add-apt-repository ppa:deadsnakes/ppa
sudo apt update
sudo apt install python3.8
sleep 1
curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
sudo python get-pip.py
sleep 1
sudo pip install bpython
sleep 1
sudo pip3 install -U scikit-learn
echo '    --->Testing Python3.8, Pip & bPython'
python3 --version
bpython --version
pip --version
sleep 1
sleep 3

#----------------------------->>> Install VirtualBox
echo " "
echo "----------------------------------------------------------------------------------"
echo "--------->      Install VirtualBox"
echo "----------------------------------------------------------------------------------"
echo " "
sleep 1
sudo add-apt-repository multiverse && sudo  apt update
sudo apt install virtualbox -y
sleep 3

#----------------------------->>> Install Discord and Slack
echo " "
echo "----------------------------------------------------------------------------------"
echo "--------->      Install Discord and Slack"
echo "----------------------------------------------------------------------------------"
echo " "
sleep 1
wget -O ./discord.deb "https://discordapp.com/api/download?platform=linux&format=deb"
sudo dpkg -i discord.deb
sleep 1
wget https://downloads.slack-edge.com/linux_releases/slack-desktop-4.0.2-amd64.deb
sudo apt install ./slack-desktop-*.deb
sleep 3

#----------------------------->>> Install Docker
echo " "
echo "----------------------------------------------------------------------------------"
echo "--------->      Install Docker and Docker Compose"
echo "----------------------------------------------------------------------------------"
echo " "
sleep 1
sudo apt install apt-transport-https ca-certificates curl -y
sleep 1
sudo curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
sleep 1
sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu  $(lsb_release -cs)  stable"
sleep 1
sudo apt-get update && sudo apt install docker-ce
sleep 1
echo '    --->Testing Docker'
    sudo docker --version 
sudo curl -L "https://github.com/docker/compose/releases/download/1.27.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
sudo ln -s /usr/local/bin/docker-compose /usr/bin/docker-compose
echo '    --->Testing Docker Compose'
    sudo docker-compose --version
sleep 3

#----------------------------->>> Install Mega.nz and DropBox
echo " "
echo "----------------------------------------------------------------------------------"
echo "--------->      Install Mega.nz and DropBox"
echo "----------------------------------------------------------------------------------"
echo " "
sleep 1
cd ~/Downloads > /dev/null
wget https://mega.nz/linux/MEGAsync/xUbuntu_18.04/amd64/megasync-xUbuntu_18.04_amd64.deb
sudo apt install -y ./megasync-xUbuntu_18.04_amd64.deb
sleep 1
echo "deb [arch=i386,amd64] http://linux.dropbox.com/ubuntu bionic main" | sudo tee -a /etc/apt/sources.list.d/dropbox.list
sudo apt-key adv --keyserver pgp.mit.edu --recv-keys 1C61A2656FB57B7E4DE0F4C1FC918B335044912E
sudo apt -f install && sudo apt update && sudo apt install python3-gpg dropbox -y
echo ""
echo "-->  Run to install Dropbox daemon"
echo "      dropbox start -i"
sleep 3

#----------------------------->>> Updating Packages
echo " "
echo "----------------------------------------------------------------------------------"
echo "--------->      Updating Packages"
echo "----------------------------------------------------------------------------------"
echo " "
sleep 1
sudo apt -f install
sudo apt update
sudo apt list --upgradable
sudo apt clean
sleep 3

#----------------------------->>> Informations
echo "If been Work Machine, remenber configure the web archives, follow:"
sleep 1
echo "ln -s ~/Dropbox/h.ssh /usr/bin/h"
sleep 1
echo "Also, in some cases, to run Tor needed reboot the system"
sleep 2
echo "Also no forget to install Zoiper in version 3.3"
sleep 2

#----------------------------->>> Install Wine
echo " "
echo -n "Do you what Install Wine and PlayOnLinux (yes/no) ? "
read opcao3
sleep 1
if [ $opcao3 = "yes" ]; then
    echo " "
    echo "----------------------------------------------------------------------------------"
    echo "--------->      Install Wine and PlayOnLinux "
    echo "----------------------------------------------------------------------------------"
    echo " "
    wget -nc https://dl.winehq.org/wine-builds/winehq.key
    sudo apt-key add winehq.key
    sudo apt-add-repository 'deb https://dl.winehq.org/wine-builds/ubuntu/ bionic main'
    sudo apt update
    sudo apt install --install-recommends winehq-stable -y
    sudo apt install playonlinux -y
    echo '    --->Testing Wine'
    wine --version
    echo '    --->Testing PlayOnLinux'
    playonlinux --version
    sleep 1
sleep 1
fi

#----------------------------->>> Install Chromecast
echo " "
echo -n "Do you what Install Chromecast (yes/no) ? "
read opcao3
sleep 1
if [ $opcao3 = "yes" ]; then
    echo " "
    echo "----------------------------------------------------------------------------------"
    echo "--------->      Install Chromecast "
    echo "----------------------------------------------------------------------------------"
    echo " "
    cd /tmp  >> /dev/null
    git clone https://github.com/Rafostar/gnome-shell-extension-cast-to-tv.git
    cd gnome-shell-extension-cast-to-tv  >> /dev/null
    git checkout pre-3.36
    make install
    sleep 1
sleep 1
fi
#----------------------------->>> Download Ubuntu

echo " "
echo -n "Do you what Download Ubuntu 18.04 LTS image for tests (yes/no) ? "
read opcao2
sleep 1
if [ $opcao2 = "yes" ]; then
    echo " "
    echo "----------------------------------------------------------------------------------"
    echo "--------->      Downloading Ubuntu 18.04 LTS image on ~/Downloads/ubuntu-18.04-LTS/ in background"
    echo "----------------------------------------------------------------------------------"
    echo " "
    sleep 1
    wget -b http://releases.ubuntu.com/18.04.3/ubuntu-18.04.3-desktop-amd64.iso -P ~/Downloads/ubuntu-18.04-LTS
    sleep 1
    echo "Run this command to view the loading of download:"
    echo "      wget -c http://releases.ubuntu.com/18.04.3/ubuntu-18.04.3-desktop-amd64.iso -P ~/Downloads/ubuntu-18.04-LTS"
    sleep 1
fi
print '\n\n\n'
echo 'MACHINE DONE'

##Install MySQL
#
#▶ sudo apt update
#▶ sudo apt upgrade
#▶ lsb_release -a
#▶ sudo apt mysql-server mysql-client
#▶ service mysql status
#▶ sudo mysql -uroot -p
#▶ ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY 'suasenha’
#▶ sudo apt install mysql-workbench
# 
# Don't forgot MongoDB Compass, MySLQ Workbench and Postbird